accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from saju.views import home

urlpatterns = [
    path('', home, name='index'),
    path("admin/", admin.site.urls),
    path("accounts/", include('accountapp.urls')),
    path("profiles/", include('profileapp.urls')),
    path("saju/", include('saju.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 추가
# urlpatterns 에 담긴 path 들 뿐만 아니라 추가로 MEDIA_URL 과 MEDIA_ROOT 를 연결시켜
# 서버가 img 를 불러올 수 있게 되어 img 가 보이게 된다

profileapp/urls.py
# pragmatic/profileapp/urls.py
from django.urls  import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

saju/urls.py
from django.urls  import path
from saju import views
from profileapp.views import ProfileCreateView, ProfileUpdateView


app_name = 'saju'

urlpatterns = [
    path('', views.home),
    path('manselyeug', views.manselyeug, name='manselyeug'),
    path('list', views.list, name='list'),
    path('write', views.write, name='write'),
    path('insert', views.insert, name='insert'),
    path('detail', views.detail, name='detail'),
    path('delete', views.delete, name='delete'),
    path('update', views.update, name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld
from saju.models import Saju

has_ownership = [account_ownership_required, login_required]

@login_required # 추가
def hello_world(request):
    if request.method == "POST":
        temp = request.POST.get('hello_world_input')
        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()
        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

@method_decorator(has_ownership,'get') # has_ownership 이라는 배열 내에 있는
@method_decorator(has_ownership,'post') # decorator 들을 모두 확인을 하고 체크 해줌.
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'

@method_decorator(has_ownership,'get') # has_ownership 이라는 배열 내에 있는
@method_decorator(has_ownership,'post') # decorator 들을 모두 확인을 하고 체크 해줌.
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{%  extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <form action="{% url 'accountapp:create' %}" method="post">
            {%  csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/delete.html
<!--pragmatic/accountapp/templates/accountapp/delete.html-->

{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align : center; max-width: 500px; margin: 4rem auto;">>
    <div class="mb-4"> <!-- margin bottom 해서 4배 -->
      <h4>Quit</h4>
    </div>
    <!--url 일원화, pk=user.pk->pk=target_user.pk 으로 수정 post 방식 으로 전송 -->
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
      {% csrf_token %}  <!-- csrf_token 은 항상 들어 가야 하는 것 -->
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html'%}

{% block content %}

  <div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
      <p>
        {{ target_user.date_joined }}
      </p>
      {% if target_user.profile %} <!--(1) profile 있고 -->
      <!--프로필 이미지를 보여주기-->
      <img src="{{ target_user.profile.image.url }}" alt=""
           style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem;">
      <h2 style="font-family: 'NanumSquareB'">
        <!--nickname 보여주기-->
        {{ target_user.profile.nickname }}
          <!-- 추가된 부분 -->
          {% if target_user == user %} <!--(1-1) target_user == user 라면-->
          <!--프로필 수정 페이지로 이동할 수 있도록-->
          <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
            edit
          </a>
          {% endif %}
          <!--------------->
      </h2>
      <!--대화명을 보여주기-->
      <h5 style="margin-bottom: 3rem;">
        {{ target_user.profile.message }}
      </h5>

      {% else %} <!--(2) profile 이 없는데-->
        <!-- 추가된 부분 -->
        {% if target_user == user %} <!-- (2-1) target_user == user 이라면-->
        <!--프로필 생성 페이지로 이동할 수 있도록-->
        <a href="{% url 'profileapp:create' %}">
          <h2 style="font-family: 'NanumSquareB'">
            Create Profile
          </h2>
        </a>
        <!-- (2-2) 단순히 프로필만 없다면-->
        {% else %}
        <h2>
          닉네임 미설정 <!--다음 출력-->
        </h2>
        {% endif %}
        <!--------------->

      {% endif %}

      {% if target_user == user %}
      <a href="{% url 'accountapp:update' pk=user.pk%}">
        <p>
          Change Info
        </p>
      </a>
      <a href="{% url 'accountapp:delete' pk=user.pk%}">
        <p>
          Quit
        </p>
      </a>
      {% endif %}
    </div>
  </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div style="border-radius: 1rem; margin: 2rem; text-align: center">
        <h1 style="font-family: 'Noto Sans KR'">
            helloworld list
        </h1>
    <form action="/accounts/hello_world/" method="post">
        {% csrf_token %}
        <div>
            <input type="text" name="hello_world_input"/>
        </div>
        <input type="submit" class="btn btn-primary" value="POST"/>
    </form>

    {% if hello_world_list %}
        {% for hello_world in hello_world_list %}
            <h6>
                {{ hello_world.text }}
            </h6>
        {% endfor %}
    {% endif %}

    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3"/>
            </form>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/update.html
{%  extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Change Info</h4>
    </div>
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {%  csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}