accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from saju.views import home

urlpatterns = [
    path('', home, name='index'),
    path("admin/", admin.site.urls),
    path("accounts/", include('accountapp.urls')),
    path("profiles/", include('profileapp.urls')),
    path("saju/", include('saju.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 추가
# urlpatterns 에 담긴 path 들 뿐만 아니라 추가로 MEDIA_URL 과 MEDIA_ROOT 를 연결시켜
# 서버가 img 를 불러올 수 있게 되어 img 가 보이게 된다

saju/urls.py
from django.urls  import path
from saju import views
from profileapp.views import ProfileCreateView, ProfileUpdateView


app_name = 'saju'

urlpatterns = [
    path('', views.home),
    path('manselyeug', views.manselyeug, name='manselyeug'),
    path('list', views.list, name='list'),
    path('write', views.write, name='write'),
    path('insert', views.insert, name='insert'),
    path('detail', views.detail, name='detail'),
    path('delete', views.delete, name='delete'),
    path('update', views.update, name='update'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}
<body style="font-family: 'NanumSquareR'">
    {% include 'header.html' %}

    <hr>
    {% block content %}

    {% endblock %}
    <hr>
    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<!--footer.html-->
    <div style="text-align:center; margin-top: 2rem;">
        <div style="font-size: .6rem;">
            <span>공지사항</span> |
            <span>제휴문의</span> |
            <span>서비스 소개</span> |
        </div>
        <div class="pragmatic_footer_logo">
            <h6 style="margin-top: 1rem">Fair Ground</h6>
        </div>
    </div>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Pragmatic</title>
    <!--BOOTSTRAP LINK-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

     <!--GOOGLE FONTS LINK-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    {#    DEFAULT CSS LINK #}
    <link rel="stylesheet" type="text/css" href = "{% static 'base.css' %}">

    <style>
    @font-face {
        font-family: 'NanumSquareR';
        src: local('NanumSqureR'),
        url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
    }
    @font-face {
        font-family: 'NanumSquareEB';
        src: local('NanumSqureEB'),
        url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
    }
    @font-face {
        font-family: 'NanumSquareB';
        src: local('NanumSqureB'),
        url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
    }
    @font-face {
        font-family: 'NanumSquareL';
        src: local('NanumSqureL'),
        url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
    }
    @font-face {
        font-family: 'malgun';
        src: local('malgun'),
        url("{% static 'fonts/malgun.ttf' %}") format("opentype");
    }
    </style>
</head>

templates/header.html
<div class="pragmatic_header">
    <div >
        <h1 class="pragmatic_logo">Fair Ground</h1>
    </div>
    <div>
        <span>nav1</span>
        <span>nav2</span>
        <a href="{% url 'saju:list' %}?next={{ request.path}}" class="pinterest_header_nav">
            <span>Saju</span>
        </a>
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path}}" class="pinterest_header_nav">
            <span>로그인</span>
        </a>

        <a href="{% url 'accountapp:create' %}" class="pinterest_header_nav">
            <span>회원가입</span>
        </a>

        {% else %}  <!-- 유저가 로그인이 되어있다면, 로그아웃 페이지를 보여주기 -->
        <a href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>마이페이지</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path}}" class="pinterest_header_nav">
            <span>로그아웃</span>
        </a>
        {% endif %}
    </div>
</div>